# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets exec'd

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
dialogBox = RsgDialog(title='Pre-design module', kernelModule='predesign', kernelFunction='Test', includeApplyBtn=False, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=thisDir)
RsgTabBook(name='TabBook_1', p='DialogBox', layout='0')
RsgTabItem(name='TabItem_5', p='TabBook_1', text='Pre-design parameter')
RsgGroupBox(name='GroupBox_14', p='TabItem_5', text='Target parameters', layout='0')
RsgTextField(p='GroupBox_14', fieldType='Float', ncols=12, labelText='Target thickness(mm):      ', keyword='targetThickness', default='')
RsgTextField(p='GroupBox_14', fieldType='Float', ncols=12, labelText='Maximum density(kg/m3):', keyword='max_density', default='')
RsgTextField(p='GroupBox_14', fieldType='Float', ncols=12, labelText='Minimum tensile modulus(Mpa):', keyword='min_tensile_modulus', default='')
RsgSeparator(p='TabItem_5')
RsgGroupBox(name='GroupBox_15', p='TabItem_5', text='FML parameters', layout='0')
RsgHorizontalFrame(name='HFrame_20', p='GroupBox_15', layout='0', pl=0, pr=0, pt=0, pb=0)
RsgGroupBox(name='GroupBox_16', p='HFrame_20', text='Metal layer', layout='0')
RsgComboBox(name='ComboBox_3', p='GroupBox_16', text='Metals:', keyword='metalCombobox', default='', comboType='STANDARD', repository='', rootText='', rootKeyword='None', layout='')
RsgTextField(p='GroupBox_16', fieldType='Float', ncols=12, labelText='Minimum thickness(mm):', keyword='m_min_thick', default='')
RsgTextField(p='GroupBox_16', fieldType='Float', ncols=12, labelText='Maximum thickness(mm):', keyword='m_max_thick', default='')
RsgGroupBox(name='GroupBox_18', p='HFrame_20', text='Polymer layer', layout='0')
RsgComboBox(name='ComboBox_4', p='GroupBox_18', text='Polymers:', keyword='polymerCombobox', default='', comboType='STANDARD', repository='', rootText='', rootKeyword='None', layout='')
materials = mdb.models['Model-1'].materials.keys()
for material in materials:
    RsgListItem(p='ComboBox_3', text=material)
    RsgListItem(p='ComboBox_4', text=material)


RsgTextField(p='GroupBox_18', fieldType='Float', ncols=12, labelText='Minimum thickness(mm):', keyword='p_min_thick', default='')
RsgTextField(p='GroupBox_18', fieldType='Float', ncols=12, labelText='Maximum thickness(mm):', keyword='p_max_thick', default='')
RsgTabItem(name='TabItem_4', p='TabBook_1', text='Geometry')
RsgLabel(p='TabItem_4', text='Default Unit(mm)', useBoldFont=False)
RsgSeparator(p='TabItem_4')
RsgVerticalFrame(name='VFrame_4', p='TabItem_4', layout='0', pl=0, pr=0, pt=0, pb=0)
RsgHorizontalFrame(name='HFrame_2', p='VFrame_4', layout='0', pl=0, pr=0, pt=0, pb=0)
RsgIcon(p='HFrame_2', fileName=r'Geometry.png')
RsgVerticalFrame(name='VFrame_3', p='HFrame_2', layout='0', pl=0, pr=0, pt=0, pb=0)
RsgGroupBox(name='GroupBox_1', p='VFrame_3', text='Whole', layout='0')
RsgTextField(p='GroupBox_1', fieldType='Float', ncols=12, labelText='Long       ', keyword='Long_Whole', default='170')
RsgTextField(p='GroupBox_1', fieldType='Float', ncols=12, labelText='Width      ', keyword='Width_Whole', default='90')
RsgTextField(p='GroupBox_1', fieldType='Float', ncols=12, labelText='Mesh size', keyword='Mesh_Size_Whole', default='1.2')
RsgGroupBox(name='GroupBox_3', p='VFrame_3', text='Center Area', layout='0')
RsgTextField(p='GroupBox_3', fieldType='Float', ncols=12, labelText='Long       ', keyword='Long_Center', default='40')
RsgTextField(p='GroupBox_3', fieldType='Float', ncols=12, labelText='Width      ', keyword='Width_Center', default='40')
RsgTextField(p='GroupBox_3', fieldType='Float', ncols=12, labelText='Mesh Size', keyword='Mesh_Size_Center', default='0.3')
RsgSeparator(p='VFrame_4')
RsgHorizontalFrame(name='HFrame_3', p='VFrame_4', layout='0', pl=0, pr=0, pt=0, pb=0)
RsgIcon(p='HFrame_3', fileName=r'Impact.png')
RsgVerticalFrame(name='VFrame_5', p='HFrame_3', layout='0', pl=0, pr=0, pt=0, pb=0)
RsgGroupBox(name='GroupBox_4', p='VFrame_5', text='Impact Head', layout='0')
RsgTextField(p='GroupBox_4', fieldType='Float', ncols=12, labelText='Radius          ', keyword='Radius', default='6.5')
RsgTextField(p='GroupBox_4', fieldType='Float', ncols=12, labelText='Speed(mm/s)', keyword='Speed', default='3200')
RsgTextField(p='GroupBox_4', fieldType='Float', ncols=12, labelText='Mesh Size     ', keyword='Mesh_Size_Impact', default='1')
RsgTextField(p='GroupBox_4', fieldType='Float', ncols=12, labelText='Total time(s): ', keyword='Total_Time', default='0.01')
dialogBox.show()